<?php

return[
    'characters'=> [
        [
            'name' => 'Maradona',
            'level' => 999,
            'class' => 'Warrior',
            'race' => 'Alien',
            'lifepoint' => 999,
            'strength' => 999,
            'agility' => 999,
            'main_weapon' => 'kick',
        
        ],
        [
            'name' => 'Jane',
            'level' => 8,
            'class' => 'Mage',
            'race' => 'Elf',
            'lifepoint' => 80,
            'strength' => 10,
            'agility' => 25,
            'main_weapon' => 'Staff',
        ],
        [
            'name' => 'Alex',
            'level' => 12,
            'class' => 'Rogue',
            'race' => 'Dwarf',
            'lifepoint' => 120,
            'strength' => 15,
            'agility' => 30,
            'main_weapon' => 'Dagger',
        ],
        [
            'name' => 'Sarah',
            'level' => 6,
            'class' => 'Paladin',
            'race' => 'Human',
            'lifepoint' => 90,
            'strength' => 18,
            'agility' => 12,
            'main_weapon' => 'Mace',
        ],
        [
            'name' => 'Mike',
            'level' => 9,
            'class' => 'Hunter',
            'race' => 'Orc',
            'lifepoint' => 110,
            'strength' => 25,
            'agility' => 20,
            'main_weapon' => 'Bow',
        ],
        [
            'name' => 'Emily',
            'level' => 5,
            'class' => 'Druid',
            'race' => 'Night Elf',
            'lifepoint' => 75,
            'strength' => 8,
            'agility' => 28,
            'main_weapon' => 'Staff',
        ],
        [
            'name' => 'David',
            'level' => 11,
            'class' => 'Warlock',
            'race' => 'Undead',
            'lifepoint' => 95,
            'strength' => 13,
            'agility' => 10,
            'main_weapon' => 'Staff',
        ],
        [
            'name' => 'Olivia',
            'level' => 7,
            'class' => 'Priest',
            'race' => 'Draenei',
            'lifepoint' => 85,
            'strength' => 5,
            'agility' => 15,
            'main_weapon' => 'Mace',
        ],
        [
            'name' => 'William',
            'level' => 14,
            'class' => 'Warrior',
            'race' => 'Human',
            'lifepoint' => 130,
            'strength' => 30,
            'agility' => 10,
            'main_weapon' => 'Axe',
        ],
        [
            'name' => 'Sophia',
            'level' => 3,
            'class' => 'Mage',
            'race' => 'Gnome',
            'lifepoint' => 60,
            'strength' => 7,
            'agility' => 18,
            'main_weapon' => 'Wand'
        ]
        ],
    'types' => [
        ['name' => 'Rimorchiatore geriatrico'],
        ['name' => 'Cecchino nelle scuole'],
        ['name' => 'Polentone'],
        ['name' => 'Terrone'],
        ['name' => 'Stronzone arcobaleno'],
        ['name' => 'Passatore di HIV'],
        ['name' => 'Donatore di 104'],
        ['name' => 'Accettore di disabilità'],
        ['name' => 'Vincitore del GayPride'],
        ['name' => 'Orgoglio Ebraico'],
    ]
        
];
